version: '3.8'

services:
  webapp:
    image: chourmovs/blissify-webapp:dev  # Utilise ton image pré-construite
    privileged: true

    volumes:
      # Monte ton dossier de développement local dans le conteneur (à ajuster selon tes besoins)
      - /app/webapp:/home/portainer/blissify/webapp:rw
      - /root/.local:/home/portainer/blissify:rw  # Monte le répertoire local dans /root/.local du conteneur
      - /var/lib/mpd:/home/portainer/blissify:rw  # Monte le répertoire local dans /var/lib/mpd du conteneur

    working_dir: /app

    ports:
      - "3000:3000"  # Expose le port de ton application Node.js

    environment:
      #NODE_ENV: development  # En mode développement
      PUID: 1000
      PGID: 1000

    #entrypoint: ["/bin/sh","-c"]
    #command:
    #-
    #   mpd
    #   npm run dev
